### ISSUE TITLE
Refactor-2022

### ISSUE THREAD

**Issue by skrmain** [skrmain/calculator#1]
## Todo

- [x] Refactor service worker, manifest and install
- [x] Update icons (fix 512px Icon)
- [x] ~~Move content of install to index.html~~
- [x] Update Buttons styling, ~~transition~~,  add border radius
- [x] ~~Fix long calculation adding scroll~~
- [x] Refactor Gulp Configuration and Remove unused Dependencies
- [x] Improve Lighthouse Audit Score

**Comment by skrmain** [comment]
## Other TODO

- [x] Add `.editorconfig`
- [x] Update Readme
